In [27]:
import function as fct
import pandas as pd
df_emission_factors = pd.read_csv("../docs/EF.csv", sep=';')
df_emission_factors_formatted = fct.format_df(df_emission_factors, ['crop_iri','fert_iri'])
df_emission_factors_formatted = df_emission_factors_formatted.drop("fert_iri",axis=1)
for crop in df_emission_factors_formatted.crop_iri.unique():
    print(df_emission_factors_formatted.query("crop_iri == @crop").drop("crop_iri",axis=1))

   climate_type  fert_type value_type  emission_factor
0           dry    default      value            0.005
1           dry    default        min            0.000
2           dry    default        max            0.011
3       default    default      value            0.010
4       default    default        min            0.001
5       default    default        max            0.018
9           wet  inorganic      value            0.016
10          wet  inorganic        min            0.013
11          wet  inorganic        max            0.019
12          wet    organic      value            0.006
13          wet    organic        min            0.001
14          wet    organic        max            0.011
15          wet   residual      value            0.006
16          wet   residual        min            0.001
17          wet   residual        max            0.011
   climate_type fert_type value_type  emission_factor
6  flooded_rice   default      value            0.004
7  flooded_rice   default        min            0.000
8  flooded_rice   default        max            0.029

In [34]:
%load_ext autoreload
%autoreload 2

from create_data import create_fertiliser_local_datastorage, create_yield_local_datastorage, create_emissionfactors_local_datastorage
create_fertiliser_local_datastorage()
#create_yield_local_datastorage()
create_emissionfactors_local_datastorage()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,climate_type,fert_type,value_type,https://vocab.sentier.dev/model-terms/nitrogen_n2o_emission_factor
0,dry,default,value,0.005
1,dry,default,min,0.000
2,dry,default,max,0.011
3,default,default,value,0.010
4,default,default,min,0.001
5,default,default,max,0.018
9,wet,inorganic,value,0.016
10,wet,inorganic,min,0.013
11,wet,inorganic,max,0.019
12,wet,organic,value,0.006
13,wet,organic,min,0.001
14,wet,organic,max,0.011
15,wet,residual,value,0.006
16,wet,residual,min,0.001
17,wet,residual,max,0.011

,climate_type,fert_type,value_type,https://vocab.sentier.dev/model-terms/nitrogen_n2o_emission_factor
6,flooded_rice,default,value,0.004
7,flooded_rice,default,min,0.000
8,flooded_rice,default,max,0.029

In [1]:
from agripeeps.n2OToAirInorganicFertiliserDirect import run

run(1,"wet")

[{'value': [0.025142857142857144],
  'min': [0.020428571428571428],
  'max': [0.029857142857142856],
  'sd': [0.002357142857142857],
  'methodModelDescription': 'Disaggregated version'}]

In [3]:
import pandas as pd

df_fertiliser_last = pd.read_csv("https://raw.githubusercontent.com/ludemannc/FUBC_1_to_9_2022/refs/heads/main/results/FUBC_9_unaggregated_crop_data.csv")

crop_lookup = df_fertiliser_last[["Crop", "Crop_UNFAO_aggregated"]].set_index("Crop").to_dict()['Crop_UNFAO_aggregated']
#crop_lookup

In [24]:
df = pd.read_csv("geonames.tsv", sep='\t')
lookup = df[["ISO3", "geonameid"]].set_index("ISO3").to_dict()['geonameid']
lookup_by_name = df[["Country", "geonameid"]].set_index("Country").to_dict()['geonameid']

In [5]:
df_fertiliser = pd.read_csv("https://raw.githubusercontent.com/ludemannc/FUBC_1_to_9_2022/refs/heads/main/results/FUBC_1_to_9_data.csv")
crops = ['Rice', 'Wheat', 'Maize', 'Potatoes']
df_fertiliser = df_fertiliser.query("Crop in @crops")
df_fertiliser['N_t_ha'] = df_fertiliser['N_k_t'] / df_fertiliser['Crop_area_k_ha']
df_fertiliser = df_fertiliser[['Crop', 'Year', 'ISO3_code', 'N_t_ha']]

In [21]:
crop_IRIs = {
    "Wheat": "http://data.europa.eu/xsp/cn2024/100100000080",
    "Rice": "http://aims.fao.org/aos/agrovoc/c_6599",	
    "Potatoe": "http://data.europa.eu/xsp/cn2024/071010000080",
    "Maize": "http://data.europa.eu/xsp/cn2024/100500000080",
    "Maize (corn)": "http://data.europa.eu/xsp/cn2024/100500000080"
}

COLUMNS = [
    "http://purl.org/dc/terms/date",
    "http://purl.org/dc/terms/Location",
    "http://data.europa.eu/xsp/cn2024/060011000090",
    "http://data.europa.eu/xsp/cn2024/310200000080"
]

In [7]:
import datetime
df_fertiliser["Year"] = df_fertiliser["Year"].str[0:4]
df_fertiliser["Country"] = df_fertiliser.ISO3_code.apply(lambda code: "https://sws.geonames.org/" + str(lookup[code]))
df_fertiliser['CropIRI'] = df_fertiliser.Crop.apply(lambda name: crop_IRIs[name])
df_fertiliser['N_kg_m2'] = df_fertiliser['N_t_ha'] * 1000 / 10000
df_fertiliser[["Year", "Country", "CropIRI", "N_kg_m2"]].set_axis(COLUMNS, axis=1)

,http://purl.org/dc/terms/date,http://purl.org/dc/terms/Location,http://data.europa.eu/xsp/cn2024/060011000090,http://data.europa.eu/xsp/cn2024/310200000080
16,1986,https://sws.geonames.org/2589581,http://data.europa.eu/xsp/cn2024/100100000080,0.003400
19,1991,https://sws.geonames.org/3351879,http://data.europa.eu/xsp/cn2024/100500000080,0.000269
36,1990,https://sws.geonames.org/2782113,http://data.europa.eu/xsp/cn2024/100500000080,0.012020
46,1990,https://sws.geonames.org/2782113,http://data.europa.eu/xsp/cn2024/100100000080,0.007986
60,1989,https://sws.geonames.org/1210997,http://data.europa.eu/xsp/cn2024/100100000080,0.005828
...,...,...,...,...
7509,2018,https://sws.geonames.org/3439705,http://data.europa.eu/xsp/cn2024/100500000080,0.014250
7513,2018,https://sws.geonames.org/3439705,http://aims.fao.org/aos/agrovoc/c_6599,0.008200
7518,2018,https://sws.geonames.org/3439705,http://data.europa.eu/xsp/cn2024/100100000080,0.011800
7521,2018,https://sws.geonames.org/1562822,http://data.europa.eu/xsp/cn2024/100500000080,0.016926
7524,2018,https://sws.geonames.org/1562822,http://aims.fao.org/aos/agrovoc/c_6599,0.012762

In [15]:
countries = df_fertiliser["ISO3_code"].unique()
years = df_fertiliser["Year"].str[0:4].unique()
crops = df_fertiliser["Crop"].unique()
crops = list(crops)
crops.remove("Maize")
crops.append("Maize (corn)")
crops

['Wheat', 'Rice', 'Maize (corn)']

In [ ]:
%pip install faostat country_converter

In [55]:
import country_converter as coco
cc = coco.CountryConverter()
cc.valid_country_classifications

['DACcode',
 'Eora',
 'FAOcode',
 'GBDcode',
 'GWcode',
 'IOC',
 'ISO2',
 'ISO3',
 'ISOnumeric',
 'UNcode',
 'ccTLD',
 'name_official',
 'name_short',
 'regex']

In [67]:
import faostat

def get_FAO_data(dataset_code, element, items, list_year):
    element_values = faostat.get_par(dataset_code, "element")
    element_number = element_values[element]
    item_values = faostat.get_par(dataset_code, "items")
    #print(item_values)
    items_number = [item_values[item] for item in items]
    data = faostat.get_data_df(
        dataset_code,
        pars={"element": element_number,
              "item": items_number,
              "year": list_year},
        coding={"area_cs": "ISO3"}
    )
    return data

def get_FAO_mean(dataset_code, element, items, list_year):
    data = get_FAO_data(dataset_code, element, items, list_year)
    # average over years
    #display(data)
    data = data.astype({"Value": "float"}).groupby(["Area", "Item"])["Value"].agg('mean')
    #data.index.name = ["Countries", "Crop"]
    return data

def fao_yield():
    data = get_FAO_data(
            dataset_code="QCL",
            element="Yield",
            items=crops,
            list_year=years,
        )
    data["ISO3"] = cc.pandas_convert(series=data["Area Code"], src="FAOcode", to='ISO3')
    data = data.query("ISO3 != 'not found'")
    #country_mapping = coco.convert(names=data["Area Code"].unique(), to="ISO3")
    #display(iso3_codes)
    #data["ISO3"] = data["Area Code"].apply(lambda code: coco.convert(names=code, to="ISO3"))
    #display(data)
    data = data[["ISO3", "Item", "Year", "Value"]]
    data["Value"] = data["Value"].astype("float")/10/10000 #convert from 100g/ha to kg/m2
    return data

fao_yields = fao_yield()

15 not found in FAOcode
41 not found in FAOcode
51 not found in FAOcode
62 not found in FAOcode
186 not found in FAOcode
276 not found in FAOcode
206 not found in FAOcode
228 not found in FAOcode
248 not found in FAOcode
5000 not found in FAOcode
5100 not found in FAOcode
5101 not found in FAOcode
5102 not found in FAOcode
5103 not found in FAOcode
5104 not found in FAOcode
5105 not found in FAOcode
5200 not found in FAOcode
5203 not found in FAOcode
5204 not found in FAOcode
5206 not found in FAOcode
5207 not found in FAOcode
5300 not found in FAOcode
5301 not found in FAOcode
5302 not found in FAOcode
5303 not found in FAOcode
5304 not found in FAOcode
5305 not found in FAOcode
5400 not found in FAOcode
5401 not found in FAOcode
5402 not found in FAOcode
5403 not found in FAOcode
5404 not found in FAOcode
5500 not found in FAOcode
5501 not found in FAOcode
5502 not found in FAOcode
5503 not found in FAOcode
5707 not found in FAOcode
5801 not found in FAOcode
5802 not found in FAOcode
5803 not found in FAOcode
5815 not found in FAOcode
5817 not found in FAOcode

In [68]:
fao_yields

      ISO3          Item  Year     Value
0      AFG  Maize (corn)  1978  0.016183
1      AFG  Maize (corn)  1984  0.016612
2      AFG  Maize (corn)  1986  0.016875
3      AFG  Maize (corn)  1987  0.017020
4      AFG  Maize (corn)  1988  0.017034
...    ...           ...   ...       ...
10127  ZWE         Wheat  2014  0.022150
10128  ZWE         Wheat  2016  0.019013
10129  ZWE         Wheat  2017  0.017542
10130  ZWE         Wheat  2018  0.027178
10131  ZWE         Wheat  2019  0.039149

[9840 rows x 4 columns]

In [71]:
fao_yields["Country"] = fao_yields.ISO3.apply(lambda code: "https://sws.geonames.org/" + str(lookup[code]))
fao_yields['CropIRI'] = fao_yields.Item.apply(lambda name: crop_IRIs[name])

COLUMNS = [
    "http://purl.org/dc/terms/date",
    "http://purl.org/dc/terms/Location",
    "http://data.europa.eu/xsp/cn2024/060011000090",
    "https://vocab.sentier.dev/model-terms/crop_yield"
]
fao_yields[["Year", "Country", "CropIRI", "Value"]].set_axis(COLUMNS, axis=1)

,http://purl.org/dc/terms/date,http://purl.org/dc/terms/Location,http://data.europa.eu/xsp/cn2024/060011000090,https://vocab.sentier.dev/model-terms/crop_yield
0,1978,https://sws.geonames.org/1149361,http://data.europa.eu/xsp/cn2024/100500000080,0.016183
1,1984,https://sws.geonames.org/1149361,http://data.europa.eu/xsp/cn2024/100500000080,0.016612
2,1986,https://sws.geonames.org/1149361,http://data.europa.eu/xsp/cn2024/100500000080,0.016875
3,1987,https://sws.geonames.org/1149361,http://data.europa.eu/xsp/cn2024/100500000080,0.017020
4,1988,https://sws.geonames.org/1149361,http://data.europa.eu/xsp/cn2024/100500000080,0.017034
...,...,...,...,...
10127,2014,https://sws.geonames.org/878675,http://data.europa.eu/xsp/cn2024/100100000080,0.022150
10128,2016,https://sws.geonames.org/878675,http://data.europa.eu/xsp/cn2024/100100000080,0.019013
10129,2017,https://sws.geonames.org/878675,http://data.europa.eu/xsp/cn2024/100100000080,0.017542
10130,2018,https://sws.geonames.org/878675,http://data.europa.eu/xsp/cn2024/100100000080,0.027178
10131,2019,https://sws.geonames.org/878675,http://data.europa.eu/xsp/cn2024/100100000080,0.039149

In [ ]:
%pip install solara

In [9]:
import pathlib
import sys
from typing import Optional, cast
import os

import pandas as pd

import solara
import solara.express as solara_px  # similar to plotly express, but comes with cross filters
import solara.lab
from solara.components.columns import Columns
from solara.components.file_drop import FileDrop

github_url = solara.util.github_url(os.path.abspath('Untitled.ipynb'))
if sys.platform != "emscripten":
    pycafe_url = solara.util.pycafe_url(path=pathlib.Path(os.path.abspath('Untitled.ipynb')), requirements=["pandas", "plotly"])
else:
    pycafe_url = None
df_sample = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv")


class State:
    size_max = solara.reactive(40.0)
    crop = solara.reactive(cast(Optional[str], None))
    country = solara.reactive(cast(Optional[str], None))
    year = solara.reactive(cast(Optional[str], None))
    df = solara.reactive(cast(Optional[pd.DataFrame], None))

    @staticmethod
    def load_sample():
        State.crop.value = "gdpPercap"
        State.country.value = "lifeExp"
        State.year.value = "lifeExp"
        State.df.value = df_sample

    @staticmethod
    def reset():
        State.df.value = None


@solara.component
def Page():
    df = State.df.value
    dark_effective = solara.lab.use_dark_effective()

    with solara.AppBar():
        solara.lab.ThemeToggle()
    
    if df is not None:
        with Columns(widths=[2, 4]):
            if State.x.value and State.y.value:
                solara_px.scatter(
                    df,
                    State.x.value,
                    State.y.value,
                    size=State.size.value,
                    color=State.color.value,
                    size_max=State.size_max.value,
                    log_x=State.logx.value,
                    log_y=State.logy.value,
                    template="plotly_dark" if dark_effective else "plotly_white",
                )
            else:
                solara.Warning("Select x and y columns")

    else:
        solara.Info("No data loaded, click on the sample dataset button to load a sample dataset, or upload a file.")

    with solara.Column(style={"max-width": "400px"}):
        solara.Button(label="View source", icon_name="mdi-github-circle", attributes={"href": github_url, "target": "_blank"}, text=True, outlined=True)
        if sys.platform != "emscripten":
            solara.Button(
                label="Edit this example live on py.cafe",
                icon_name="mdi-coffee-to-go-outline",
                attributes={"href": pycafe_url, "target": "_blank"},
                text=True,
                outlined=True,
            )


@solara.component
def Layout(children):
    route, routes = solara.use_route()
    dark_effective = solara.lab.use_dark_effective()
    return solara.AppLayout(children=children, toolbar_dark=dark_effective, color=None)  # if dark_effective else "primary")

Layout([Page()])

Cannot show ipywidgets in text